Ignore private methods for binary types during type assertion
traefik/yaegi pull request #1374
Opened 2022-04-06 08:57 UTC by cclerget

Fixes #1373

2022-04-06 08:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/traefik/yaegi?pullRequest=1374) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/traefik/yaegi?pullRequest=1374) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/traefik/yaegi?pullRequest=1374) it.</sub>

2022-04-07 07:21 UTC, cclerget commented
Note: simplified test case by using `go/ast`

2022-04-07 07:21 UTC, cclerget commented
Note: simplified test case by using `go/ast`

2022-04-07 15:50 UTC, mvertes requested changes
Beside comment punctuation, looks good to me.

2022-04-07 16:14 UTC, mvertes approved these changes

2022-04-07 16:16 UTC, merged