chore: adds a downloader script.
traefik/yaegi pull request #855
Opened 2020-09-18 15:18 UTC by ldez

2020-09-19 14:53 UTC, mvertes requested changes
I do not understand exactly why this `godownloader.sh` script is required. Why do we need to include it ?

May be some use instructions need to be added in `README.md` ?

It could be better to rename `godownloader.sh` in `install.sh`, for clarity, as in http://golangci/golangci-lint.
As this script is itself generated, a rule to rebuild it (if we change the list of supported archictectures) needs to be added in `Makefile` .

2020-09-20 12:04 UTC, ldez commented
The goal is to be able to easily use the Yaegi command line in a CI.
This will be very useful for Traefik plugins creators, or for anyone who wants to use an interpreted script in a CI.

2020-09-20 16:22 UTC, mvertes reviewed
Ok, thanks. LGTM.

2020-09-20 16:23 UTC, mvertes approved these changes

2020-09-20 16:26 UTC, merged